/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWebhooksWahaRouteImport } from './routes/api/public/webhooks/waha'
import { Route as ApiPublicWahaStopRouteImport } from './routes/api/public/waha/stop'
import { Route as ApiPublicWahaStartRouteImport } from './routes/api/public/waha/start'
import { Route as ApiPublicWahaSendRouteImport } from './routes/api/public/waha/send'
import { Route as ApiPublicWahaPairRouteImport } from './routes/api/public/waha/pair'
import { Route as ApiPublicAiTestRouteImport } from './routes/api/public/ai/test'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksWahaRoute = ApiPublicWebhooksWahaRouteImport.update({
  id: '/api/public/webhooks/waha',
  path: '/api/public/webhooks/waha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWahaStopRoute = ApiPublicWahaStopRouteImport.update({
  id: '/api/public/waha/stop',
  path: '/api/public/waha/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWahaStartRoute = ApiPublicWahaStartRouteImport.update({
  id: '/api/public/waha/start',
  path: '/api/public/waha/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWahaSendRoute = ApiPublicWahaSendRouteImport.update({
  id: '/api/public/waha/send',
  path: '/api/public/waha/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWahaPairRoute = ApiPublicWahaPairRouteImport.update({
  id: '/api/public/waha/pair',
  path: '/api/public/waha/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiTestRoute = ApiPublicAiTestRouteImport.update({
  id: '/api/public/ai/test',
  path: '/api/public/ai/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/ai/test': typeof ApiPublicAiTestRoute
  '/api/public/waha/pair': typeof ApiPublicWahaPairRoute
  '/api/public/waha/send': typeof ApiPublicWahaSendRoute
  '/api/public/waha/start': typeof ApiPublicWahaStartRoute
  '/api/public/waha/stop': typeof ApiPublicWahaStopRoute
  '/api/public/webhooks/waha': typeof ApiPublicWebhooksWahaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/ai/test': typeof ApiPublicAiTestRoute
  '/api/public/waha/pair': typeof ApiPublicWahaPairRoute
  '/api/public/waha/send': typeof ApiPublicWahaSendRoute
  '/api/public/waha/start': typeof ApiPublicWahaStartRoute
  '/api/public/waha/stop': typeof ApiPublicWahaStopRoute
  '/api/public/webhooks/waha': typeof ApiPublicWebhooksWahaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/ai/test': typeof ApiPublicAiTestRoute
  '/api/public/waha/pair': typeof ApiPublicWahaPairRoute
  '/api/public/waha/send': typeof ApiPublicWahaSendRoute
  '/api/public/waha/start': typeof ApiPublicWahaStartRoute
  '/api/public/waha/stop': typeof ApiPublicWahaStopRoute
  '/api/public/webhooks/waha': typeof ApiPublicWebhooksWahaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/ai-assistant'
    | '/automations'
    | '/billing'
    | '/campaigns'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/whatsapp'
    | '/api/public/ai/test'
    | '/api/public/waha/pair'
    | '/api/public/waha/send'
    | '/api/public/waha/start'
    | '/api/public/waha/stop'
    | '/api/public/webhooks/waha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/ai-assistant'
    | '/automations'
    | '/billing'
    | '/campaigns'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/whatsapp'
    | '/api/public/ai/test'
    | '/api/public/waha/pair'
    | '/api/public/waha/send'
    | '/api/public/waha/start'
    | '/api/public/waha/stop'
    | '/api/public/webhooks/waha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/automations'
    | '/_authenticated/billing'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/whatsapp'
    | '/api/public/ai/test'
    | '/api/public/waha/pair'
    | '/api/public/waha/send'
    | '/api/public/waha/start'
    | '/api/public/waha/stop'
    | '/api/public/webhooks/waha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAiTestRoute: typeof ApiPublicAiTestRoute
  ApiPublicWahaPairRoute: typeof ApiPublicWahaPairRoute
  ApiPublicWahaSendRoute: typeof ApiPublicWahaSendRoute
  ApiPublicWahaStartRoute: typeof ApiPublicWahaStartRoute
  ApiPublicWahaStopRoute: typeof ApiPublicWahaStopRoute
  ApiPublicWebhooksWahaRoute: typeof ApiPublicWebhooksWahaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/waha': {
      id: '/api/public/webhooks/waha'
      path: '/api/public/webhooks/waha'
      fullPath: '/api/public/webhooks/waha'
      preLoaderRoute: typeof ApiPublicWebhooksWahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waha/stop': {
      id: '/api/public/waha/stop'
      path: '/api/public/waha/stop'
      fullPath: '/api/public/waha/stop'
      preLoaderRoute: typeof ApiPublicWahaStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waha/start': {
      id: '/api/public/waha/start'
      path: '/api/public/waha/start'
      fullPath: '/api/public/waha/start'
      preLoaderRoute: typeof ApiPublicWahaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waha/send': {
      id: '/api/public/waha/send'
      path: '/api/public/waha/send'
      fullPath: '/api/public/waha/send'
      preLoaderRoute: typeof ApiPublicWahaSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waha/pair': {
      id: '/api/public/waha/pair'
      path: '/api/public/waha/pair'
      fullPath: '/api/public/waha/pair'
      preLoaderRoute: typeof ApiPublicWahaPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/test': {
      id: '/api/public/ai/test'
      path: '/api/public/ai/test'
      fullPath: '/api/public/ai/test'
      preLoaderRoute: typeof ApiPublicAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAiTestRoute: ApiPublicAiTestRoute,
  ApiPublicWahaPairRoute: ApiPublicWahaPairRoute,
  ApiPublicWahaSendRoute: ApiPublicWahaSendRoute,
  ApiPublicWahaStartRoute: ApiPublicWahaStartRoute,
  ApiPublicWahaStopRoute: ApiPublicWahaStopRoute,
  ApiPublicWebhooksWahaRoute: ApiPublicWebhooksWahaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
